language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install flake8 pytest
script:
  - python -m pytest
  - python -m flake8
deploy:
  provider: pypi
  user: sfzhou
  on:
    branch: master
  skip_existing: true
